version: "3.8"
services:
  backend:
    build: ./backend
    command: /bin/sh -c "chmod +x entrypoint.sh && ./entrypoint.sh"
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/docker-todo/backend
    depends_on:
      - db
    tty: true
    stdin_open: true
    environment:
      - DATABASE_HOST=db
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=password
  frontend:
    build: ./frontend
    command: sh -c "npm start"
    ports:
      - "8000:3000"
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend
  db:
    platform: linux/x86_64
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql
volumes:
  db-volume:
